name: Deploy index.html files to Web Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy index.html files
        run: |
          scp 3dMaps/1f_embed.html ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/mnt/docker/volumes/njs-webserver/_data/lingnan-library-3d/1f/index.html
          scp 3dMaps/2f_embed.html ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/mnt/docker/volumes/njs-webserver/_data/lingnan-library-3d/2f/index.html
          scp 3dMaps/3f_embed.html ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/mnt/docker/volumes/njs-webserver/_data/lingnan-library-3d/3f/index.html
          scp 3dMaps/mf_embed.html ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/mnt/docker/volumes/njs-webserver/_data/lingnan-library-3d/mf/index.html
